// This code was generated by gtgen 0.0.1
#pragma once
#include <gmock/gmock.h>
#include <iostream>
#include <string>

class mock_hogehoge : public hogehoge {
 public:
  MOCK_CONST_METHOD2(class_inherit_function_bar, int(int,std::string const));
  
};


