// This code was generated by gtgen 0.0.1
#pragma once
#include <gmock/gmock.h>
#include <iostream>
#include <string>

class mock_hoge {
 public:
  ~mock_hoge() = default;
  static mock_hoge& GetInstance() {
    static mock_hoge instance;
    return instance;
  }
  MOCK_METHOD2(class_function_bar, int(int,std::string const));
  
 private:
  mock_hoge() = default;
};

int hoge::class_function_bar (int a, std::string const b) {
  return mock_hoge::GetInstance().class_function_bar(a, b);
}

