// This code was generated by gtgen 0.0.1
#pragma once

#include <gmock/gmock.h>

#include "FunctionInfo.h"
#include "IncludeInfo.h"
#include "ScopeInfo.h"
#include <string>
#include <unordered_map>
#include <vector>


class mock_CodeAnalyzerInterface : public CodeAnalyzerInterface {
 public:
  MOCK_METHOD0(GetFunctions, std::vector<std::shared_ptr<FunctionAttributeInterface>>());
  MOCK_METHOD0(GetScopes, std::vector<ScopeInfo>());
  MOCK_METHOD0(GetIncludes, std::vector<IncludeInfo>());
};

